config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create,:index,:update]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create', as: 'post_login'
  patch 'users/update/:id', to: 'users#update', as: 'user_update'
  get 'users/edit/:id', to: 'users#edit', as: 'user_edit'
  root to: 'sessions#welcome', as: 'welcome'

  get 'organization', to: 'organization#index', as: 'organization_index'
  get 'organization/show', to: 'organization#show', as: 'organization_show'
  get 'organization/new', to: 'organization#new', as: 'organization_new'
  post 'organization/store', to: 'organization#store', as: 'organization_store'
  get 'organization/:id/edit', to: 'organization#edit', as: 'organization_edit'
  patch 'organization/:id/update', to: 'organization#update', as: 'organization_update'
  delete 'organization/:id/delete', to: 'organization#delete', as: 'organization_delete'

  get 'organization/:id/person', to: 'person#index', as: 'person_index'
  get 'organization/:id/person/new', to: 'person#new', as: 'person_new'
  post 'organization/:id/person/store', to: 'person#store', as: 'person_store'
  get 'organization/:organization_id/person/edit/:id', to: 'person#edit', as: 'person_edit'
  patch 'organization/:organization_id/person/edit/:id', to: 'person#update', as: 'person_update'
  delete 'organization/:organization_id/person/delete/:id', to: 'person#delete', as: 'person_delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'authorized', to: 'sessions#page_requires_login'
  delete '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
  mount_uploader :logo, ImageUploader
end

app/models/person.rb
class Person < ApplicationRecord
  self.table_name = 'person'
  mount_uploader :avatar, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :organizations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/' unless logged_in?
  end

end

app/controllers/organization_controller.rb
class OrganizationController < ApplicationController
  def index
    @organization = Organization.all
  end

  def show
  end

  def new
    @new = Organization.new

  end

  def store
    @store = Organization.new(organization_params)

    if @store.save

      redirect_to organization_index_path, notice: 'Organization berhasil ditambahkan'
    else
      render :new
    end

  end

  def edit
    @edit = Organization.find(params[:id])

  end

  def update
    @update = Organization.find(params[:id])
    if @update.update(organization_params)
      redirect_to organization_index_path, notice: 'Organization berhasil diupdate'
    else
      render :edit
    end
  end

  def delete
    @delete = Organization.find(params[:id])
    if @delete.destroy
      redirect_to organization_index_path(params[:id]), notice: 'Organization berhasil dihapus'
    else
      render person_index_path(params[:organization_id])
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :phone, :email, :website, :logo)
  end

end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
    @person = Person.where(organization_id: params[:id])
  end

  def edit
    @edit = Person.find(params[:id])
  end

  def update
    @update = Person.find(params[:id])
    if @update.update(person_params)
      redirect_to person_index_path(params[:organization_id]), notice: 'Person berhasil diupdate'
    else
      render :edit

    end
  end

  def new
    @new = Person.new

  end

  def store
    @store = Person.new(person_params)

    if @store.save

      redirect_to person_index_path, notice: 'Person berhasil ditambahkan'
    else
      render :new
    end
  end

  def delete
    @delete = Person.find(params[:id])
    if @delete.destroy
      redirect_to person_index_path(params[:organization_id]), notice: 'Person berhasil dihapus'
    else
      render person_index_path(params[:organization_id])
    end
  end

  def person_params
    params.require(:person).permit(:name, :phone, :email, :avatar, :organization_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
    @user = User.new

  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to welcome_path
    else
      redirect_to login_path
    end

  end

  def login
  end

  def welcome
  end

  def page_requires_login
  end

  def destroy
    User.find(session[:user_id])
    session[:user_id] = nil
    redirect_to welcome_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username,
                                                     :password))
    session[:user_id] = @user.id
    redirect_to welcome_path

  end

  def edit
    @edit = User.find(params[:id])
    @organization = Organization.all
  end

  def update
    @update = User.find(params[:id])
    if @update.update(user_params)
      redirect_to users_path
    end
  end

  def index
    @user = User.joins("left join organizations on users.account_manager = organizations.id").select(:'id', :'username', :'role', :'organizations.name')
  end

  def user_params
    params.require(:user).permit(:username, :role, :account_manager)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organization_helper.rb
module OrganizationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "printerous" %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "About Sharks" %>">
</head>

<body>
<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
          <title>Bootstrap</title>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path>
        </svg>
        <span class="fs-4">printerous</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <% if logged_in? %>
          <%= link_to 'Organization', organization_index_path, :class => 'me-3 py-2 text-dark text-decoration-none' %>
          <% if current_user.role == 'admin' %>
            <%= link_to 'Users', users_path, :class => 'me-3 py-2 text-dark text-decoration-none' %>

          <% end %>
          <%= link_to "Log out", logout_path, method: "delete", :class => 'me-3 py-2 text-dark text-decoration-none' %>
        <% end %>
      </nav>
    </div>
  </header>
  <%= yield %>

</div>
</body>
</html>

app/views/organization/edit.html.erb
<%= form_with model: @edit, url: organization_update_path, multipart: true do |f| %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= f.text_field :name, placeholder: 'Nama Organization', :class => 'form-control', :id => 'name' %>
  </div>
  <div class="mb-3">
    <label for="phone" class="form-label">Phone</label>
    <%= f.text_field :phone, placeholder: 'No Telpon Organization', :class => 'form-control', :id => 'phone' %>
  </div>
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <%= f.text_field :email, placeholder: 'Email', :class => 'form-control', :id => 'phone', :type => 'email' %>
  </div>
  <div class="mb-3">
    <label for="website" class="form-label">Website</label>
    <%= f.text_field :website, placeholder: 'Website', :class => 'form-control', :id => 'phone', :type => 'text' %>
  </div>
  <div class="mb-3">
    <label for="logo" class="form-label">Logo</label>
    <%= f.text_field :logo, placeholder: 'Logo', :class => 'form-control', :id => 'phone', :type => 'file' %>
  </div>



  <%= f.submit 'Update' %>
<% end %>

app/views/organization/index.html.erb
<div class="d-flex justify-content-between bd-highlight">
  <div class="p-2 bd-highlight">
    <h3>List Organization</h3>

  </div>
  <div class="p-2 bd-highlight">
    <% if logged_in? %>
      <% if current_user.role == 'admin' %>
        <%= link_to 'Create', organization_new_path, :class => 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
</div>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Phone</th>
    <th scope="col">Email</th>
    <th scope="col">Website</th>
    <th scope="col">Logo</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @organization.each_with_index do |data, index| %>

    <tr>
      <td><%= index += 1 %></td>
      <td><%= data.name %></td>
      <td><%= data.phone %></td>
      <td><%= data.email %></td>
      <td><%= data.website %></td>
      <td><img src="<%= data.logo %>" alt="Avatar" class="avatar">
      </td>
      <td>
        <%= link_to 'Person', person_index_path(data.id), :class => 'btn btn-success' %>
        <% if logged_in? %>
          <% if current_user.role == 'admin' || (current_user.role == 'account_manager' && current_user.account_manager == data.id) %>
            <%= link_to 'Edit', organization_edit_path(data.id), :class => 'btn btn-primary' %>
            <%= link_to 'Hapus', organization_delete_path(data.id), data: { confirm: 'Ingin menghapus data ini?' }, method: :delete, :class => 'btn btn-danger' %>
          <% end %>
        <% end %>
      </td>
    </tr>

  <% end %>
  </tbody>

</table>

app/views/organization/new.html.erb
<%= form_with model: @new, url: organization_store_path, multipart: true do |f| %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= f.text_field :name, placeholder: 'Nama Organization', :class => 'form-control', :id => 'name' %>
  </div>
  <div class="mb-3">
    <label for="phone" class="form-label">Phone</label>
    <%= f.text_field :phone, placeholder: 'No Telpon Organization', :class => 'form-control', :id => 'phone' %>
  </div>
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <%= f.text_field :email, placeholder: 'Email', :class => 'form-control', :id => 'phone', :type => 'email' %>
  </div>
  <div class="mb-3">
    <label for="website" class="form-label">Website</label>
    <%= f.text_field :website, placeholder: 'Website', :class => 'form-control', :id => 'phone', :type => 'text' %>
  </div>
  <div class="mb-3">
    <label for="logo" class="form-label">Logo</label>
    <%= f.text_field :logo, placeholder: 'Logo', :class => 'form-control', :id => 'phone', :type => 'file' %>
  </div>



  <%= f.submit 'Tambah' %>
<% end %>

app/views/organization/show.html.erb
<h1>Organization#show</h1>
<p>Find me in app/views/organization/show.html.erb</p>

app/views/person/delete.html.erb
<h1>Person#delete</h1>
<p>Find me in app/views/person/delete.html.erb</p>

app/views/person/edit.html.erb
<%= form_with model: @edit, url: person_update_path, multipart: true do |f| %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= f.text_field :name, placeholder: 'Nama ', :class => 'form-control', :id => 'name' %>
  </div>
  <div class="mb-3">
    <label for="phone" class="form-label">Phone</label>
    <%= f.text_field :phone, placeholder: 'No Telpon ', :class => 'form-control', :id => 'phone' %>
  </div>
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <%= f.text_field :email, placeholder: 'Email', :class => 'form-control', :id => 'phone', :type => 'email' %>
  </div>

  <div class="mb-3">
    <label for="logo" class="form-label">Avatar</label>
    <%= f.text_field :avatar, placeholder: 'Avatar', :class => 'form-control', :id => 'avatar', :type => 'file' %>
    <%= f.text_field :organization_id, placeholder: 'Avatar', :value => params[:organization_id], :class => 'form-control', :id => 'avatar', :type => 'hidden' %>
  </div>
  <%= f.submit 'Update' %>
<% end %>

app/views/person/index.html.erb
<div class="d-flex justify-content-between bd-highlight">
  <div class="p-2 bd-highlight">
    <h3>List Person</h3>

  </div>
  <div class="p-2 bd-highlight">
    <% if logged_in? %>
      <% if current_user.role == 'admin' || (current_user.role == 'account_manager' && current_user.account_manager == data.organization_id) %>
        <%= link_to 'Create', person_new_path, :class => 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
</div>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Phone</th>
    <th scope="col">Email</th>
    <th scope="col">Avatar</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @person.each do |data, index| %>

    <tr>
      <td><%= data.id %></td>
      <td><%= data.name %></td>
      <td><%= data.phone %></td>
      <td><%= data.email %></td>
      <td><img src="<%= data.avatar %>" alt="Avatar" class="avatar">
      </td>
      <td>
        <% if logged_in? %>
          <% if current_user.role == 'admin' || (current_user.role == 'account_manager' && current_user.account_manager == data.organization_id) %>

            <%= link_to 'Edit', person_edit_path(data.organization_id, data.id), :class => 'btn btn-primary' %>
            <%= link_to 'Hapus', person_delete_path(data.organization_id, data.id), data: { confirm: 'Ingin menghapus data ini?' }, method: :delete, :class => 'btn btn-danger' %>
          <% end %>
        <% end %>
      </td>
    </tr>

  <% end %>
  </tbody>

</table>

app/views/person/new.html.erb
<%= form_with model: @new, url: person_store_path, multipart: true do |f| %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= f.text_field :name, placeholder: 'Nama ', :class => 'form-control', :id => 'name' %>
  </div>
  <div class="mb-3">
    <label for="phone" class="form-label">Phone</label>
    <%= f.text_field :phone, placeholder: 'No Telpon ', :class => 'form-control', :id => 'phone' %>
  </div>
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <%= f.text_field :email, placeholder: 'Email', :class => 'form-control', :id => 'phone', :type => 'email' %>
  </div>

  <div class="mb-3">
    <label for="logo" class="form-label">Avatar</label>
    <%= f.text_field :avatar, placeholder: 'Avatar', :class => 'form-control', :id => 'avatar', :type => 'file' %>
    <%= f.text_field :organization_id, placeholder: 'Avatar', :value => params[:id], :class => 'form-control', :id => 'avatar', :type => 'hidden' %>
  </div>




  <%= f.submit 'Tambah' %>
<% end %>

app/views/person/store.html.erb
<h1>Person#store</h1>
<p>Find me in app/views/person/store.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<%= form_with model: @edit, url: user_update_path do |f| %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= f.text_field :username, placeholder: 'Nama ', :class => 'form-control', :id => 'name' %>
  </div>
  <div class="mb-3">
    <label for="name" class="form-label">Role</label>
    <%= f.select :role, [['Please select an option', nil], 'admin', 'account_manager'], {}, { :class => 'form-control' } %>
  </div>
  <div class="mb-3">
    <label for="name" class="form-label">Organization</label>
    <%= f.select :account_manager, Organization.all.map { |c| [c.name, c.id] }, { :prompt => "Select One" }, { :class => 'form-control' } %>
  </div>




  <%= f.submit 'Update' %>
<% end %>

app/views/users/index.html.erb
<div class="d-flex justify-content-between bd-highlight">
  <div class="p-2 bd-highlight">
    <h3>List Organization</h3>

  </div>
  <div class="p-2 bd-highlight">

  </div>
</div>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Role</th>
    <th scope="col">Account Manager</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @user.each_with_index do |data, index| %>

    <tr>
      <td><%= index += 1 %></td>
      <td><%= data.username %></td>
      <td><%= data.role %></td>
      <td><%= data.name %></td>
      <td>
        <% if logged_in? %>
          <% if current_user.role == 'admin' %>
            <%= link_to 'Edit', user_edit_path(data.id), :class => 'btn btn-primary' %>
            <%= link_to 'Hapus', organization_delete_path(data.id), data: { confirm: 'Ingin menghapus data ini?' }, method: :delete, :class => 'btn btn-danger' %>
          <% end %>
        <% end %>
      </td>
    </tr>

  <% end %>
  </tbody>

</table>

app/views/users/new.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-4">
    <%= form_for @user do |f| %>

      <div class="text-center mb-4">
        <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">User register</h1>
      </div>

      <div class="form-label-group p-2">
        <label for="inputEmail">Username</label>
        <%= f.text_field :username, :class => 'form-control' %>
      </div>

      <div class="form-label-group p-2 mb-2">
        <label for="inputPassword">Password</label>
        <%= f.password_field :password, :class => 'form-control' %>

      </div>

      <div class="text-center ">
        <%= f.submit 'Sign up', :class => 'btn btn-lg btn-primary btn-block' %>

        <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2018</p>

      </div>
    <% end %>
  </div>
</div>